baseURL = 'https://username.github.io/prompt/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = 'Prompts Space'
theme = 'hugo-coder'
enableEmoji = true

[pagination]
pagerSize = 10

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Prompts Space"
description = "AI æ”¹å˜ä¸–ç•Œï¼Œpromptæ”¹å˜AI"
keywords = "blog,AI,prompt,å¼€å‘è€…,ä¸ªäºº"
info = ["å…¨æ ˆå¼€å‘/æµ‹è¯•æ¶æ„å¸ˆ/Pythoner", "AIä¸“å®¶"]
dateFormat = "2006å¹´1æœˆ2æ—¥"
since = 2024
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/"

[languages.zh-cn]
languageName = "ğŸ‡¨ğŸ‡³"

[[languages.zh-cn.menu.main]]
name = "å…³äº"
weight = 1
url = "about/"

[[languages.zh-cn.menu.main]]
name = "åšå®¢"
weight = 2
url = "posts/"

[[languages.zh-cn.menu.main]]
name = "é¡¹ç›®"
weight = 3
url = "projects/"

[[languages.zh-cn.menu.main]]
name = "è”ç³»"
weight = 5
url = "contact/"
